[package]
name = "crabers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bevy-inspector-egui = "0.21.0"
bevy-inspector-egui-rapier = {version = "0.9.0",  features=["rapier2d"]}
bevy_pancam = "0.10.0"
bevy_rapier2d = {version = "0.23.0", features = ["simd-stable",  "parallel"]}
rand = "0.8.5"
